FROM python:3.9-slim

WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the entire current directory to /app in the container
COPY . .

# Command to run the Python script
CMD ["python", "process_data.py"]